import java.util.ArrayList;

public class Airport

{

    /** A list of the flights into and out of this airport

     *   Guaranteed not to be null and to contain only non-null entries

     */

    private ArrayList<Flight> allFlights;



    /** Returns the revenue generated by all flights at the airport, as described in part (a) */

    public double getTotalRevenue()

    {
        double count= 0;
        for(int i=0;i<allFlights.size();i++)
        {
            int numOfPassenger= allFlights.get(i).getNumPassengers();
            double prices = allFlights.get(i).getPrice();
            int capacity  =  allFlights.get(i).getCapacity();
            if(capacity<numOfPassenger)
            {
                count+=prices*capacity;

            }
            else {
                count+=prices*numOfPassenger;

            }

        }
        return count;
    }
    public int updateFlights()
    {
        int count=0;

        for(int i=0;i<allFlights.size();i++)
        {
            if((double)allFlights.get(i).getNumPassengers()/allFlights.get(i).getCapacity()<0.2)
            {
                count+=allFlights.get(i).getNumPassengers();
                allFlights.remove(i);
            }
        }
        return count;
    }
    public Flight getMostL





    /** Updates the list of flights by removing certain flights and returns the total number of

     *   passengers whose flights were removed, as described in part (b)

     */

    public int updateFlights()

    {  /* to be implemented in part (b) */  }



// There may be instance variables, constructors, and methods that are not shown.

}